package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/tkdn/go-study/domain"
	"github.com/tkdn/go-study/graph/model"
	"github.com/tkdn/go-study/log"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*domain.User, error) {
	u, err := r.UserRepo.Insert(ctx, input.Name, input.Age)
	if err != nil {
		log.Logger.Error(err.Error())
		return nil, err
	}
	return u, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*domain.Post, error) {
	p, err := r.PostRepo.Insert(ctx, input.UserID, input.Text)
	if err != nil {
		return nil, err
	}
	return p, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*domain.User, error) {
	users, err := r.UserRepo.GetList(ctx)
	if err != nil {
		log.Logger.Error(err.Error())
		return nil, err
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int) (*domain.User, error) {
	u, err := r.UserRepo.GetById(ctx, id)
	if err != nil {
		log.Logger.Error(err.Error())
		return nil, err
	}
	return u, nil
}

// Post is the resolver for the post field.
func (r *userResolver) Post(ctx context.Context, obj *domain.User) ([]*domain.Post, error) {
	p, err := r.PostRepo.GetListByUserID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return p, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
