// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	UserID int    `json:"userId"`
	Text   string `json:"text"`
}

type NewUser struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type Query struct {
}
